# Generated by Django 5.2 on 2025-07-22 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EjemploUsu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejemplouso',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
